---
- name: Ensure Lutris registry is available
  apt_repository:
    repo: 'ppa:lutris-team/lutris'
    state: present
  become: yes

- name: Install list of game packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - lutris