
- name: Install list of required packages
  apt:
    update_cache: yes
    name: "{{item}}"
    state: latest
  become: yes
  with_items:
    - git
    - subversion 
    - docker.io
    - docker-compose
