---
- name: Install list of required packages
  apt:
    update_cache: yes
    name: "{{item}}"
    state: latest
  become: yes
  with_items:
    - unace
    - unrar
    - zip
    - unzip
    - p7zip-full
    - p7zip-rar
    - sharutils
    - rar
    - uudeview
    - mpack
    - arj
    - cabextract
