---
- name: Install list of sysadmin packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - ansible
    - multiboot
    - gparted
    - screen
    - tmux
    - netcat
    - keepassxc