---
- name: Ensure Nextcloud registry is available
  apt_repository:
    repo: 'ppa:nextcloud-devs/client'
    state: present
  become: yes

- name: Install list of communication packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - nextcloud-client
    - mumble