
- name: Add atom repository
  become: yes
  apt_repository:
    repo: 'ppa:webupd8team/atom'
  
- name: Install list of required packages
  apt:
    update_cache: yes
    name: "{{item}}"
    state: latest
  become: yes
  with_items:
    - vim
    - gedit-developer-plugins
    - gedit-plugins
    - atom
    - kate
   
