
- name: Workspace folder creation
  file:
    path: $HOME/Workspace
    state: directory
- name: Install list of required packages
  apt:
    update_cache: yes
    name: "{{item}}"
    state: latest
  become: yes
  with_items:
    - build-essential
    - chromium-browser
    - firefox
    - curl
    - ubuntu-restricted-extras
    - wget
    - htop
    - iotop
    - silversearcher-ag
    - owncloud-client
    - language-pack-kde-fr
    - openjdk-9-jre
    - tree
