---
- name: Workspace folder creation
  file:
    path: $HOME/Workspace
    state: directory
- name: Install list of common packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - build-essential
    - curl
    - ubuntu-restricted-extras
    - wget
    - htop
    - iotop
    - silversearcher-ag
    - language-pack-kde-fr
    - tree
    - redshift