---
- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{ item }}"
    update_cache: yes
  become: yes
  with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Ensure repository key is installed
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    keyserver: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  become: yes

- name: Get the release name
  shell: 'lsb_release -cs'
  register: release_name

- name: Ensure Docker registry is available
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release_name.stdout }} stable'
    state: present
  become: yes

- name: Ensure docker and dependencies are installed
  apt:
    update_cache: yes
    name: "{{ item }}"
  become: yes
  with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- service:
    name: docker
    state: restarted